# Generated by Django 4.1.7 on 2023-03-23 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0001_initial"),
        ("owner", "0001_initial"),
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produitmodel",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="products",
                to="category.categorymodel",
            ),
        ),
        migrations.AlterField(
            model_name="produitmodel",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="produitmodel",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="products",
                to="owner.productownermodel",
            ),
        ),
        migrations.DeleteModel(
            name="CategoryModel",
        ),
        migrations.DeleteModel(
            name="ProductOwnerModel",
        ),
    ]
