# Generated by Django 4.1.7 on 2023-03-29 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("owner", "0001_initial"),
        ("category", "0001_initial"),
        ("image", "0002_alter_imagemodel_alt"),
        ("discount", "0002_alter_discountmodel_product"),
        ("product", "0002_alter_produitmodel_category_alter_produitmodel_id_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ProduitModel",
            new_name="ProductModel",
        ),
    ]
