# Generated by Django 4.1.7 on 2023-03-23 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("product", "0002_alter_produitmodel_category_alter_produitmodel_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiscountModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=80)),
                ("description", models.CharField(blank=True, max_length=160)),
                ("rate", models.FloatField()),
                ("start_date", models.DateTimeField(auto_now_add=True, null=True)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="discounts",
                        to="product.produitmodel",
                    ),
                ),
            ],
        ),
    ]
