# Generated by Django 4.1.7 on 2023-03-23 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_alter_produitmodel_category_alter_produitmodel_id_and_more"),
        ("discount", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discountmodel",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="discounts",
                to="product.produitmodel",
            ),
        ),
    ]
