# Generated by Django 4.1.7 on 2023-03-29 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("product", "0003_rename_produitmodel_productmodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="StockMoveModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "type",
                    models.CharField(
                        choices=[("IN", "IN"), ("OUT", "OUT")], max_length=3
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StockMoveItemModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField()),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_move_items",
                        to="product.productmodel",
                    ),
                ),
                (
                    "stock_move",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="stock.stockmovemodel",
                    ),
                ),
            ],
        ),
    ]
