# Generated by Django 4.1.7 on 2023-03-29 14:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0002_remove_stockmoveitemmodel_quantity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockmovemodel",
            name="date",
            field=models.DateField(
                default=datetime.datetime(2023, 3, 29, 16, 14, 39, 375724)
            ),
        ),
    ]
