# Generated by Django 4.1.7 on 2023-03-29 14:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0003_alter_stockmovemodel_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockmovemodel",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 3, 29, 16, 24, 26, 959113)
            ),
        ),
    ]
