# Generated by Django 4.1.7 on 2023-03-29 15:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0004_alter_stockmovemodel_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockmovemodel",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="stockmovemodel",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 3, 29, 17, 7, 47, 237056)
            ),
        ),
    ]
