# Generated by Django 4.1.7 on 2023-03-30 08:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0005_stockmovemodel_price_alter_stockmovemodel_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockmovemodel",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 3, 30, 10, 12, 56, 139145)
            ),
        ),
    ]
