# Generated by Django 4.1.7 on 2023-03-30 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("owner", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productownermodel",
            name="name",
            field=models.CharField(max_length=80, unique=True),
        ),
    ]
